script: bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: lp9h+sC+eIhPHlVBZdZyvz1T9P6Ut/U1X0g6/ndOEjXouEokidjdVUZc1QAFJ9K1wSvf+TFaCx2xpO+HiH2MZyZnZkGR/tPIMfyS6pJjEvuqkR4sXy1BAOQp4Dtn5Xrqt9uKPoZuttHLrO4OhMa9+gIapA1J+0TJeHKqcys9PKpKJxlYkbYEMBT3P+JnrQQAfpnceoZgD1pYaCBgcZeI1MVBVbl4y/c+bIxTMY/9lCwJF/uesfHFP8nodRCmjyGMKvlmNdOvHRbsFrxN2Vn0EJebUmIQwowtgIdNSm+GUEPahSRr5sINYxoFnLMSAdTZGgXHpsQFrJEUFygviQQC6RfqQ16F1RH9IH3NbU4h/cfHtu7L3JfeJRN5rsKjiWy/hfAUL3AT7ydSpfEmRca3QF5FqxeyLZAW4i5jn23QCfDkUBWBFBGpZ6ZdAG8O8E2sTqw09ZFebd4vJ3gxJypmpY35PrhRRPWLTroWsjkI+J2yYkQP7Nu5DuvQmmzjpD/YIoU15/2S742DctsUPMfSGvChdP0EQXg0qvYtkqTVQJUTSzX/MTXrp4vkgbqebWi06LERXpLEskLYwJAFCITfa9s5ItRtUQSfWXru57rytxM9/rgVzHSMmAWe4GTo2FI8Uz2Xj9M6UPFKRuXV0JssbYBHPD5eXvd/CKz8WJI9lkk=
app: murmuring-coast-92613
 

