script: bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: LbUJJZB5sOMb8bi5g2wRnC3XoMM1phod24GaoOpmXnj9vplUGFpCTEXIzphHFPBObn9TjBBn9ghksKrVBNiYGX7XnNgVCfsnhmzTC0BQRUk7NlxSW3xc6/Z06Llubu71FoaOaPW+SGQ0etVwohUVGrsGaO6+5NNdbUO2xvGMvdF8a0zKTGf/Gd5QEP58QRnm7wMAKNGHXwMlHw3W1ZgbF4OD0PfXIMOZmmtJ/AQcIOGha6Opx5402wbGS2yGj47rzWFLcT5Kxck21Unk2RtU1Au1HBv8ixykqUA0iLks+QqRLnxRiaiHSJiV06+u0NuUmYw+ujT3a6je1cxNR5e/uyKJ3qAbNSzpPpVah5v2Me9YTnENq1jvmmpinBHgqn078f7QpMpVg1UXWLL0XHqzLAoPoxKqKqcZnPXfdqUdTYs0nrbgX0iyzLGnY/VsQQoInZ5+FT0HtlkYYmL/uZx/Mj6cBQIl0tp/iWjlCNBrJixe/5MFlY4IsopK8fQ9JO2ndomuFczROW1wm15c7V5aZKZtoBgeU5Z3TRJ+tb8hLyQzbgas78s+tpSEZoc6VuKzQEFEnT7OUO2qoAigdHx2WGd20FnNzN3xs4sSE7oK9uZeoSPgbVPSp7dM++HzY41MxOT/Ibd2Yw8hJZANRQapDHJwYHfHWQy0jMiiZKWlamc=
  app: murmuring-coast-92613

