script: bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: VJMuK0d5IFYgGlXw3HmIFo6a4YODSCFxesSNeyezcO6ENL2x4TYFJlmZyc9c0vWU3q6+Izr8Uhh9K18xPsBd1FHBqjGiCq+CXL/Qjh6jZPP6Y68yeW4hmq/QU0mvuKbZBx6opWiGbG648s3mD3G9mLoQbCscyqcpE+3+V63S8dx3u3Vtg5nxftr8f9M0KSg3Ksuc/pwxSSDUQT94P7siJDzwJ7tbQs75ArwNWxZwak3w96LaAOn4xF5nwoDux/1Ul7lZYsLkTt4cRG9leUUPC5z7bLxDMURc9sWiQCSxY5bOV6bZ/m/bC/TT8g+zT5kNeXiSIr/2iICK08181bgQtgzaydUhFCXcGZto1EBEdqN70sE2lZaYh0WzInzbnxhtasiR2Zx5D2feIoC4HbwGmX9/+MEkKRcgVWnyrDMKghwmEmlUbpfbUnx3kLqO/P/2rHhZoHk+bRktt/ET6OO+S22rwXNK4RkxcKzdPqN30dqsHwiYxTYwUxyihgS8ArgJtyUCXikmZSOqG01SvxL01eBbaajDnyT/LRnw0WNHkHBdH7b+duFulecCQPMdqOS4dmhlVd6rmGu7lvJOEs5nF9pTcVTxfN2FQxXJH0oSpylBT6F4FNtL7qnMXaFzcIu/3FFG0FbypS0s1x0ttz4TKRPM1XljOZQMIPboRG3i1yk=
app: murmuring-coast-92613
